Task 2
V-Ivanich/project_Fast-company pull request #2
Opened 2022-11-17 05:36 UTC by V-Ivanich

вроде работает )))

2022-11-17 15:27 UTC, AndreiSachuk requested changes
Смотри, надо исправлять, много недоработок
Открою тебе решения автора, что бы понятнее стало
И исходя из низ причеши свой код

2022-11-17 15:27 UTC, AndreiSachuk commented on src/App.js
> +            {users.map(user => (
считаю, что не верно)
у тебя в юзерсах должны быть строк, а в юзере - уже конкретная строка

2022-11-17 15:27 UTC, AndreiSachuk commented on src/App.js
> +                users={user}
а то ты в компонент Users преедаещ user, при этом пропс обхываешь users

2022-11-17 15:27 UTC, AndreiSachuk commented on src/components/users.jsx
> +      <tr key={users._id}>
users - множественное число, а как у массива может быть _id?
это отсылка к тому, что написал в файле app

2022-11-17 15:27 UTC, AndreiSachuk commented on src/components/users.jsx
> +          users={users}
и снова в компонент User  передаешь users

2022-11-17 15:27 UTC, AndreiSachuk commented on src/components/user.jsx
> +      color={elem.color}
следи за вложенностью, читсается очень тяжело

2022-11-17 15:27 UTC, AndreiSachuk commented on src/components/user.jsx
> +      color={elem.color}
тут ты передаешь 3 элемента через elem.   возможно стоит пересмотреть подход, но не обязательно)

2022-11-17 15:27 UTC, AndreiSachuk commented on src/components/user.jsx
> +        <td>{users.rate}</td>
тейтинг там был    4/5   например , не просто цифра

2022-11-17 15:27 UTC, AndreiSachuk commented on src/components/bookMark.jsx
> +    <button className="btn rounded-pill btn-light" onClick={()=> props.onMark(getSetMark(props.idItem))}>
props.onMark   а чего не вся логика тут?

2022-11-17 17:58 UTC, V-Ivanich commented on src/components/users.jsx
> +          users={users}
fixed

2022-11-17 18:01 UTC, V-Ivanich commented on src/App.js
> +                users={user}
fixed

2022-11-17 18:09 UTC, V-Ivanich commented on src/components/user.jsx
> +      color={elem.color}
fixed

2022-11-18 07:51 UTC, V-Ivanich commented on src/components/user.jsx
> +        <td>{users.rate}</td>
вроде все через точку значиния...

2022-11-18 07:51 UTC, V-Ivanich commented on src/components/bookMark.jsx
> +    <button className="btn rounded-pill btn-light" onClick={()=> props.onMark(getSetMark(props.idItem))}>
по заданию было -"Вынести состояния и методы в компонент App"

2022-11-18 09:35 UTC, AndreiSachuk requested changes

2022-11-18 09:35 UTC, AndreiSachuk commented on src/App.js
> +    const listItems = users.map(userItems => {
ну тогда уже user или userInfo ну или userItem)))

2022-11-18 09:35 UTC, AndreiSachuk commented on src/App.js
> +                usersItems={usersItem}
usersItems={usersItem} 
именование просто капец  usersItems !== usersItem   по правилам языка))

2022-11-18 09:35 UTC, AndreiSachuk commented on src/App.js
> +                usersItems={usersItem}
Очень важно давать правильные названия, потом сам себе будешь голову ломать и не понимать что проихсодило, через 2 дня

2022-11-18 09:35 UTC, AndreiSachuk commented on src/components/users.jsx
> +          user={usersItems}
user={usersItems}

user - единственное число     =    usersItems    users - множественное число, items - множественное число
не пойдет, думай о своей психике)

2022-11-18 14:59 UTC, AndreiSachuk requested changes
Начгни с коомента app.js 51 строка

2022-11-18 14:59 UTC, AndreiSachuk commented on src/components/user.jsx
> +    <td> {users.qualities.map(userElem =>
вот посмотри на эту строку, у users разве может быть qualities?

2022-11-18 14:59 UTC, AndreiSachuk commented on src/components/user.jsx
> +    <td> {users.qualities.map(userElem =>
qualities есть у userа одного, но не у многих

2022-11-18 14:59 UTC, AndreiSachuk commented on src/components/user.jsx
> +    <td>{users.rate}</td>
rate - он должен быть 2 / 5, а не просто 2

2022-11-18 14:59 UTC, AndreiSachuk commented on src/components/users.jsx
> +      <tr key={usersItems._id}>
аналогичная история....
как у множественного числа может быть id?

2022-11-18 14:59 UTC, AndreiSachuk commented on src/App.js
> +            {users.map(usersItems => (
смотри, users,map содержит массив юзеров, соответственно каждый элемент массива, это не usersItems, а userItem или User!

понимаешь??

2022-11-19 07:11 UTC, V-Ivanich commented on src/components/user.jsx
> +    <td>{users.rate}</td>
упс, я не допер,- просмотрел виде еще раз и увидел...

2022-11-20 17:21 UTC, AndreiSachuk approved these changes

2022-11-20 18:32 UTC, merged